/* Claimmap public data. Official doors from USA.gov / NAUPA (scraped 19 Aug 2026). */
window.CM_STATES = {"us":[{"id":"AL","name":"Alabama","url":"https://alabama.findyourunclaimedproperty.com/"},{"id":"AK","name":"Alaska","url":"http://treasury.dor.alaska.gov/Unclaimed-Property.aspx"},{"id":"AZ","name":"Arizona","url":"https://azdor.gov/unclaimed-property/"},{"id":"AR","name":"Arkansas","url":"https://auditor.ar.gov/"},{"id":"CA","name":"California","url":"https://sco.ca.gov/upd_msg.html"},{"id":"CO","name":"Colorado","url":"https://colorado.findyourunclaimedproperty.com/"},{"id":"CT","name":"Connecticut","url":"https://ctbiglist.gov/"},{"id":"DE","name":"Delaware","url":"https://unclaimedproperty.delaware.gov/"},{"id":"DC","name":"District of Columbia","url":"https://dc.findyourunclaimedproperty.com/"},{"id":"FL","name":"Florida","url":"https://fltreasurehunt.gov/index.jsp"},{"id":"GA","name":"Georgia","url":"https://dor.georgia.gov/unclaimed-property-program"},{"id":"HI","name":"Hawaii","url":"https://budget.hawaii.gov/finance/unclaimedproperty/"},{"id":"ID","name":"Idaho","url":"https://yourmoney.idaho.gov/"},{"id":"IL","name":"Illinois","url":"https://icash.illinoistreasurer.gov/"},{"id":"IN","name":"Indiana","url":"https://indianaunclaimed.gov/"},{"id":"IA","name":"Iowa","url":"https://www.iowatreasurer.gov/for-citizens/great-iowa-treasure-hunt/"},{"id":"KS","name":"Kansas","url":"https://kansascash.ks.gov/"},{"id":"KY","name":"Kentucky","url":"https://treasury.ky.gov/Pages/index.aspx"},{"id":"LA","name":"Louisiana","url":"http://LaCashClaim.org"},{"id":"ME","name":"Maine","url":"https://maineunclaimedproperty.gov/"},{"id":"MD","name":"Maryland","url":"https://www.marylandtaxes.gov/unclaimed-property/index.php"},{"id":"MA","name":"Massachusetts","url":"https://www.findmassmoney.com/"},{"id":"MI","name":"Michigan","url":"https://unclaimedproperty.michigan.gov/"},{"id":"MN","name":"Minnesota","url":"https://mn.gov/commerce/consumers/your-money/find-missing-money/"},{"id":"MS","name":"Mississippi","url":"https://treasury.ms.gov/for-citizens/unclaimed-property/"},{"id":"MO","name":"Missouri","url":"https://treasurer.mo.gov/UnclaimedProperty/"},{"id":"MT","name":"Montana","url":"https://mtrevenue.gov/"},{"id":"NE","name":"Nebraska","url":"https://treasurer.nebraska.gov/up/"},{"id":"NV","name":"Nevada","url":"https://www.nevadatreasurer.gov/Unclaimed_Property/UP_Home/"},{"id":"NH","name":"New Hampshire","url":"https://newhampshire.findyourunclaimedproperty.com/"},{"id":"NJ","name":"New Jersey","url":"https://www.unclaimedproperty.nj.gov/"},{"id":"NM","name":"New Mexico","url":"https://www.tax.newmexico.gov/Individuals/search-unclaimed-property.aspx"},{"id":"NY","name":"New York","url":"https://www.osc.state.ny.us/ouf/index.htm"},{"id":"NC","name":"North Carolina","url":"https://www.nccash.com/"},{"id":"ND","name":"North Dakota","url":"https://www.land.nd.gov/UnclaimedProperty/"},{"id":"OH","name":"Ohio","url":"https://www.com.ohio.gov/unfd/"},{"id":"OK","name":"Oklahoma","url":"https://www.oktreasure.com/"},{"id":"OR","name":"Oregon","url":"https://oregon.findyourunclaimedproperty.com/"},{"id":"PA","name":"Pennsylvania","url":"https://www.patreasury.gov/"},{"id":"RI","name":"Rhode Island","url":"https://findrimoney.com/"},{"id":"SC","name":"South Carolina","url":"https://www.treasurer.sc.gov/what-we-do/for-citizens/unclaimed-property-program/"},{"id":"SD","name":"South Dakota","url":"https://southdakota.findyourunclaimedproperty.com/"},{"id":"TN","name":"Tennessee","url":"https://treasury.tn.gov/Unclaimed-Property/Claim-Unclaimed-Property/Find-Your-Missing-Money"},{"id":"TX","name":"Texas","url":"https://claimittexas.org/"},{"id":"UT","name":"Utah","url":"https://mycash.utah.gov/"},{"id":"VT","name":"Vermont","url":"https://www.vermonttreasurer.gov/content/unclaimed-property"},{"id":"VA","name":"Virginia","url":"https://vamoneysearch.org/"},{"id":"WA","name":"Washington","url":"https://ucp.dor.wa.gov/"},{"id":"WV","name":"West Virginia","url":"https://www.wvtreasury.com/"},{"id":"WI","name":"Wisconsin","url":"https://www.revenue.wi.gov/Pages/UnclaimedProperty/Home.aspx"},{"id":"WY","name":"Wyoming","url":"https://statetreasurer.wyo.gov/UnclaimedProperty.aspx"},{"id":"PR","name":"Puerto Rico","url":"https://www.prb.uscourts.gov/?q=unclaimed-funds"},{"id":"GU","name":"Guam","url":"http://doa.guam.gov/treasurer-of-guam/"},{"id":"VI","name":"U.S. Virgin Islands","url":"https://ltg.gov.vi/departments/unclaimed-property/"}],
"other":[{"id":"AB","name":"Alberta","url":"https://www.alberta.ca/unclaimed-property.aspx"},{"id":"BC","name":"British Columbia","url":"https://unclaimedpropertybc.ca/"},{"id":"QC","name":"Quebec","url":"https://www.revenuquebec.ca/en/unclaimed-property/"},{"id":"BOC","name":"Bank of Canada","url":"https://www.bankofcanada.ca/unclaimed-balances/"},{"id":"HK","name":"Hong Kong — MPFA","url":"https://www.mpfa.org.hk/en"},{"id":"HKOR","name":"Hong Kong — Official Receiver","url":"https://www.oro.gov.hk/"}]};

window.CM_METHODS = [
  {id:"state",name:"State unclaimed property",kind:"claim",region:"us",capital:0,score:5,
    blurb:"Dormant accounts, old paychecks, utility deposits. The one reel claim that is actually true — and already free.",
    cost:"$0",time:"1 hour to search; weeks to pay",
    legal:"You may only claim property you own, or that an estate you legally represent owns. Search is free on official sites. Never pay an upfront finder fee.",
    steps:["Search every state you lived or worked in. Start with MissingMoney, then the official state site.","Match name + city. Similar-name hits are common — do not claim what is not yours.","File only on the official state site. Keep a copy of the claim number.","Heirs need a death certificate and probate / small-estate papers."],
    links:[["USA.gov index","https://www.usa.gov/unclaimed-money"],["NAUPA","https://unclaimed.org/search/"],["MissingMoney","https://missingmoney.com/"]]},
  {id:"irs",name:"IRS tax refund",kind:"claim",region:"us",capital:0,score:5,
    blurb:"If you filed and the refund never arrived, the tracker is free. Stimulus claim windows are closed.",
    cost:"$0",time:"15 minutes",
    legal:"There is a limited time to claim a credit or refund. Check IRS timing rules. This is not a secret pot of unclaimed stimulus.",
    steps:["Use IRS Where’s My Refund or your IRS online account.","Have SSN/ITIN, filing status, exact refund amount, tax year.","Lost check: request a refund trace after the normal wait.","Do not give tax info to a random ‘refund finder’."],
    links:[["IRS refunds","https://www.irs.gov/refunds"]]},
  {id:"pbgc",name:"Unclaimed private pension",kind:"claim",region:"us",capital:0,score:5,
    blurb:"If a former employer’s defined-benefit plan ended, PBGC may be holding the benefit.",
    cost:"$0",time:"20 minutes + documents",
    legal:"Search uses last name + last 4 of SSN on the official PBGC site only. Database updates quarterly.",
    steps:["Search PBGC unclaimed retirement benefits.","Also search DOL unpaid wages if a paycheck never arrived.","Gather old W-2s and plan statements.","Never type your SSN into a random locator site."],
    links:[["PBGC search","https://www.pbgc.gov/workers-retirees/find-unclaimed-retirement-benefits/search-unclaimed"],["DOL unpaid wages","https://webapps.dol.gov/wow/"]]},
  {id:"hud",name:"FHA mortgage refund",kind:"claim",region:"us",capital:0,score:4,
    blurb:"Some paid-off or refinanced FHA loans generate a refund. Most people have $0 here.",
    cost:"$0",time:"15 minutes",legal:"Only if you had FHA insurance and HUD shows a balance.",
    steps:["Search the HUD FHA refund database.","Have old case numbers and addresses.","Ignore paid ads that ‘find HUD money’ for a cut."],
    links:[["HUD FHA refunds","https://entp.hud.gov/dsrs/refunds/"]]},
  {id:"banks",name:"Closed bank or credit union",kind:"claim",region:"us",capital:0,score:4,
    blurb:"Failed institutions leave unclaimed deposits — only if you actually banked there.",
    cost:"$0",time:"20 minutes",legal:"Official FDIC and NCUA lists only. Funds often also escheat to the state.",
    steps:["Search FDIC closed-bank unclaimed funds.","Search NCUA unclaimed deposits.","Also run state unclaimed property."],
    links:[["FDIC","https://closedbanks.fdic.gov/funds/"],["NCUA","https://ncua.gov/support-services/conservatorships-liquidations/unclaimed-deposits"]]},
  {id:"va",name:"VA + civilian life insurance",kind:"claim",region:"us",capital:0,score:4,
    blurb:"Veterans’ unclaimed VA insurance, plus the NAIC locator for civilian policies. Family / named beneficiaries only.",
    cost:"$0",time:"30 minutes",legal:"Not a civilian windfall. Heirs need a death certificate.",
    steps:["Search VA unclaimed insurance funds if veteran / surviving family.","Use the NAIC Life Insurance Policy Locator for civilian policies.","Do not pay a ‘policy finder’ an upfront fee."],
    links:[["VA search","https://insurance.va.gov/UnclaimedFunds/Search"],["NAIC locator","https://eapps.naic.org/life-policy-locator/"]]},
  {id:"courts",name:"Court, SEC, and bankruptcy leftovers",kind:"claim",region:"us",capital:0,score:3,
    blurb:"You must have been a creditor, harmed investor, or entitled party. Not ‘free court money’.",
    cost:"$0–copies",time:"Days to weeks",legal:"Official locators only.",
    steps:["Search the U.S. Courts Unclaimed Funds Locator.","Check SEC harmed-investor distributions if you lost money in a fraud case.","File the official claim packet."],
    links:[["US Courts","https://ucf.uscourts.gov/"],["SEC harmed investors","https://www.sec.gov/enforce/information-for-harmed-investors"]]},
  {id:"bonds",name:"Old savings bonds",kind:"claim",region:"us",capital:0,score:4,
    blurb:"Matured paper bonds still exist. The public Treasury Hunt search tool shut down 30 Sep 2025.",
    cost:"$0",time:"Forms + weeks",legal:"Use TreasuryDirect claim forms for lost, stolen, or destroyed bonds.",
    steps:["Do not hunt for a live Treasury Hunt search — it is gone.","Gather serial numbers and names if you have them.","File official replacement / claim forms.","Paper bonds in a drawer: value calculator, then redeem."],
    links:[["Treasury Hunt status","https://www.treasurydirect.gov/savings-bonds/treasury-hunt/"],["Bond forms","https://www.treasurydirect.gov/savings-bonds/forms/"]]},
  {id:"iim",name:"Individual Indian Money accounts",kind:"claim",region:"us",capital:0,score:4,
    blurb:"BTFA manages IIM accounts for Native American and Alaska Native beneficiaries. Whereabouts-unknown search is official.",
    cost:"$0",time:"30 minutes",legal:"Only for entitled beneficiaries.",
    steps:["Use the Department of the Interior Whereabouts Unknown search.","Follow BTFA claim instructions.","Do not use a paid intermediary."],
    links:[["IIM accounts","https://www.doi.gov/ost/iim-accounts"],["Whereabouts Unknown","https://www.doi.gov/ost/wau"]]},
  {id:"ibonds",name:"I Bonds — investing, not found money",kind:"tax",region:"us",capital:25,score:5,
    blurb:"Inflation-linked US savings bonds. $25 minimum electronic. Annual cap. This is buying a Treasury product.",
    cost:"$25+",time:"1 hour",legal:"Federal tax on interest. 12-month lockup. Penalty if cashed before 5 years.",
    steps:["Open a TreasuryDirect account.","Buy electronic I Bonds. Know the calendar-year limit.","Do not confuse this with unclaimed cash."],
    links:[["I Bonds","https://www.treasurydirect.gov/savings-bonds/i-bonds/"]]},
  {id:"tips",name:"TIPS — not a Buffett secret",kind:"tax",region:"us",capital:100,score:4,
    blurb:"Treasury Inflation-Protected Securities. $100 minimum. Principal adjusts with CPI.",
    cost:"$100+",time:"Account + auction calendar",legal:"Federal tax each year on interest and inflation adjustments. No state/local tax.",
    steps:["Read the TreasuryDirect TIPS page. Terms are 5, 10, or 30 years.","Buy at auction or via a broker / TIPS ETF.","A ‘ladder’ is just staggered maturities."],
    links:[["TreasuryDirect TIPS","https://www.treasurydirect.gov/marketable-securities/tips/"]]},
  {id:"augusta",name:"14-day home rental (IRC §280A(g))",kind:"tax",region:"us",capital:0,score:3,
    blurb:"Rent your residence 14 days or fewer and that rent can be excluded from income — with no rental deductions either.",
    cost:"Real business + fair rent + records",time:"A tax year",
    legal:"26 U.S.C. § 280A(g). Renting to your own company is marketed hard and audited. Need substance, market rate, minutes, invoices. Talk to a CPA. Not legal advice.",
    steps:["Read the statute, not a reel. 14 days is a hard cap.","Fair rental. Written agreement. Proof the space was used.","Do not double-dip home-office and party-rental days.","This is a tax exclusion, not a cash machine."],
    links:[["26 U.S.C. § 280A","https://www.law.cornell.edu/uscode/text/26/280A"]]},
  {id:"sam",name:"SAM.gov contracting — a job, not a pile of cash",kind:"work",region:"us",capital:0,score:3,
    blurb:"Real path to sell to the US government. Not unclaimed no-bid contracts waiting for you.",
    cost:"Time + ability to deliver",time:"Weeks to register; months to first award",
    legal:"FAR 13.2 lets agencies buy under the micro-purchase threshold without full competition if the price is reasonable. That is the government buying supplies — not free money.",
    steps:["Get login.gov + a Unique Entity ID on SAM.gov.","Register the entity and keep it active.","Search solicitations you can actually perform.","Ignore ‘$800 billion they must give away’ scripts."],
    links:[["SAM.gov","https://sam.gov/content/home"],["FAR 13.2","https://www.acquisition.gov/far/subpart-13.2"]]},
  {id:"lodge",name:"Volunteer lodging — work for housing",kind:"work",region:"us",capital:0,score:3,
    blurb:"Some federal volunteer roles include housing. You work. You are not gifted a mansion.",
    cost:"$0 + labor",time:"Application + season",legal:"Volunteer.gov is the official board. Lodging-offered is a filter, not a deed.",
    steps:["Open Volunteer.gov. Filter lodging offered.","Read dates, duties, who provides food or hookup.","Apply like a job. Background checks are normal."],
    links:[["Volunteer.gov","https://volunteer.gov/"]]},
  {id:"taxsale",name:"Tax-delinquent lists",kind:"property",region:"us",capital:1000,score:2,
    blurb:"Counties publish lists. You are not buying someone’s life for $100. You are buying a lien or deed with redemption rights, title clouds, and often occupants.",
    cost:"Taxes + penalties + lawyer + repairs",time:"Months to years",
    legal:"State-specific. Redeeming owners often get the property back. Quiet title is a lawsuit. Get a local real-estate attorney.",
    steps:["Find your county treasurer list. Read the statute.","Know lien vs deed state and the redemption period.","Budget a lawyer. Walk the property.","If a reel said ‘free house’, close the reel."],
    links:[["USA.gov (start)","https://www.usa.gov/unclaimed-money"]]},
  {id:"car",name:"Abandoned-vehicle process",kind:"property",region:"us",capital:100,score:2,
    blurb:"States have lien statutes. They are not a $50 luxury-SUV vending machine.",
    cost:"Tow, storage, notices, title fees",time:"Weeks + statutory notice",
    legal:"Police report, registered-owner notice, DMV forms. Skipping notice is conversion.",
    steps:["Read your state DMV abandoned-vehicle page.","Lot owners and tow operators follow the posted process.","A passer-by who ‘found’ a dusty SUV does not own that car."],
    links:[["USA.gov","https://www.usa.gov/unclaimed-money"]]},
  {id:"drive",name:"Vehicle transport gigs",kind:"income",region:"us",capital:0,score:3,
    blurb:"Driveaway work is a job. You get paid to move someone else’s car.",
    cost:"Deposits, sometimes CDL, empty return",time:"Ongoing labor",legal:"You are a contractor. Fuel deals vary. Read the contract.",
    steps:["Treat this as employment, not a loophole.","Confirm insurance, deposits, and who pays fuel.","Budget the trip home — that is why the Instagram number is fake."],
    links:[["USA.gov","https://www.usa.gov/"]]},
  {id:"media",name:"Stock photo / rain audio",kind:"income",region:"intl",capital:0,score:2,
    blurb:"Real market. Brutally saturated. ‘$35,000 a month from 31-second rain clips’ is a hook, not a median.",
    cost:"$0–software",time:"Months of volume + luck",legal:"You must own the recording. Platform TOS apply.",
    steps:["Original recordings only. Clean metadata. Many assets.","Treat any 5-figure monthly claim as marketing until you see tax returns.","This is a creative business, not unclaimed money."],
    links:[["U.S. Copyright Office","https://www.copyright.gov/"]]},
  {id:"liq",name:"Retail liquidation pallets",kind:"income",region:"us",capital:1000,score:2,
    blurb:"Real. Also full of broken returns. You need storage, shipping, and a channel.",
    cost:"$500–$5,000+ per pallet",time:"Ongoing ops",legal:"Resale certificates, platform rules, no unsafe goods.",
    steps:["Use known liquidation marketplaces. Start tiny.","Model worst-case: a large share unsellable.","This is merchandising, not a government loophole."],
    links:[["SAM.gov is not this","https://sam.gov/content/home"]]},
  {id:"geo",name:"Foreign high-yield bank account",kind:"warn",region:"intl",capital:100,score:1,
    blurb:"High nominal rates exist. They come with FX, deposit-insurance limits, tax residency, and political risk. Not ‘12% from the kitchen, no downside’.",
    cost:"Capital + possible FBAR / 8938 if a US person",time:"Weeks",
    legal:"US persons must report foreign accounts over thresholds. Not legal advice.",
    steps:["Talk to a cross-border tax advisor first.","Read deposit insurance and currency.","A 12% local-currency rate is not a 12% USD rate after FX."],
    links:[["TreasuryDirect (US alternative)","https://www.treasurydirect.gov/"]]},
  {id:"aged",name:"Aged corporations / credit stacking",kind:"warn",region:"us",capital:1000,score:1,
    blurb:"Buying a shell with ‘seasoned credit’ is a staple of fraud videos. Banks treat it as misrepresentation.",
    cost:"High. Legal risk higher.",time:"Skip",legal:"Do not buy someone else’s corporate identity to get credit.",
    steps:["Need business credit? Form your own entity and build it.","Report scams that sell aged corps as a product."],
    links:[["SAM.gov entity registration (legit)","https://sam.gov/content/home"]]},
  {id:"hkmpf",name:"Hong Kong MPF / old jobs",kind:"claim",region:"hk",capital:0,score:4,
    blurb:"Old Hong Kong jobs leave MPF accounts behind. Check MPFA and your trustees — not a Facebook claim agent.",
    cost:"$0",time:"1–2 hours + trustee wait",legal:"Only the member or entitled party. Macau has no US-style 50-state grid.",
    steps:["Search MPFA public information for lost / unclaimed accounts.","Contact the trustee on old statements.","Keep HKID / passport ready."],
    links:[["MPFA","https://www.mpfa.org.hk/en"]]},
  {id:"hkor",name:"HK Official Receiver / court money",kind:"claim",region:"hk",capital:0,score:3,
    blurb:"Insolvency processes sometimes hold unclaimed dividends. Only if you were a creditor or entitled party.",
    cost:"$0–certified copies",time:"Days to months",legal:"Official Receiver’s Office and Judiciary notices. Not a public ATM.",
    steps:["Search Official Receiver’s Office notices.","Write with proof if you had a claim in a liquidation.","For Macau, use the actual bank / employer / DSSS — there is no MissingMoney clone."],
    links:[["Official Receiver’s Office","https://www.oro.gov.hk/"]]}
];

window.CM_REELS = [
  {hook:"“I got a free house from a county list nobody read.”",
   verdict:"Mostly false",score:2,
   truth:"Counties do publish tax-delinquent lists. You buy a lien or a deed. Owners often have a redemption period. Title is cloudy. Occupants exist. Lawyers are not optional. ‘Free’ is the hook; the all-in cost is taxes + penalties + legal + repairs."},
  {hook:"“Luxury SUV in a parking structure — legally mine for $50.”",
   verdict:"False for a passer-by",score:1,
   truth:"Abandoned-vehicle statutes require notice to the registered owner and a DMV process. A dusty car in a garage is still that owner’s car. Skipping notice is conversion, not a loophole."},
  {hook:"“Rain sounds: $35,000 a month in streaming royalties.”",
   verdict:"Outlier marketing",score:2,
   truth:"Platforms pay fractions of a cent per stream, often after 30 seconds. $35k/month implies enormous, sustained plays. The market is saturated. This is a creative business, not unclaimed money."},
  {hook:"“The feds lost $800 billion and must give it away.”",
   verdict:"False",score:1,
   truth:"Unspent appropriations are not a public ATM. SAM.gov is how vendors sell to the government. FAR 13.2 lets agencies buy small items without full competition if the price is reasonable — they are buying staplers, not mailing you a check."},
  {hook:"“Georgian bank, 12% interest, from my kitchen table.”",
   verdict:"Incomplete to the point of misleading",score:1,
   truth:"High nominal rates exist in some currencies. They come with FX, deposit-insurance limits, tax residency, and — for US persons — FBAR / Form 8938 reporting. 12% local currency is not 12% USD."},
  {hook:"“The government will pay you to live in a million-dollar estate.”",
   verdict:" volunteer housing, not a deed",score:2,
   truth:"Volunteer.gov lists federal roles. Some include lodging. You work. You do not receive title to an estate. Competitive, seasonal, background-checked."},
  {hook:"“They stopped paying rent. I bought their entire life for $100.”",
   verdict:"Fiction-shaped",score:1,
   truth:"Quiet title is a lawsuit. Tax sales have statutory bids, notices, and redemption. $100 is a thumbnail number, not a closing statement."},
  {hook:"“Get paid $6,000 a month to drive cars you’ll never own.”",
   verdict:"A gig, not a loophole",score:3,
   truth:"Driveaway / dispatch work exists. You are labor. Fuel, empty return, deposits, and insurance eat the Instagram number."},
  {hook:"“10-foot forgotten strip. Sold an easement for $15,000.”",
   verdict:"Only if you already own the land",score:2,
   truth:"Easements are real. Most people do not own a forgotten sliver. You need a survey, a willing buyer (often a utility or neighbor), and a lawyer. GIS curiosity is not title."},
  {hook:"“Every state is sitting on billions they’ll keep forever.”",
   verdict:"The true part — then they sell a PDF",score:5,
   truth:"States do hold unclaimed property. They want owners to claim it. Official search is free on USA.gov, NAUPA, and MissingMoney. You do not need a $27 ebook to be handed the .gov link."}
];

window.CM_WEEK = [
  ["mm","Search MissingMoney for your name","https://missingmoney.com/"],
  ["naupa","Open NAUPA and hit every state you have lived in","https://unclaimed.org/search/"],
  ["irs","Check IRS Where’s My Refund / online account","https://www.irs.gov/refunds"],
  ["pbgc","Search PBGC unclaimed pensions","https://www.pbgc.gov/workers-retirees/find-unclaimed-retirement-benefits/search-unclaimed"],
  ["dol","Search DOL unpaid wages","https://webapps.dol.gov/wow/"],
  ["hud","HUD FHA refunds if you ever had an FHA loan","https://entp.hud.gov/dsrs/refunds/"],
  ["fdic","FDIC + NCUA if a bank or CU of yours failed","https://closedbanks.fdic.gov/funds/"],
  ["va","VA insurance if veteran / surviving family","https://insurance.va.gov/UnclaimedFunds/Search"],
  ["naic","NAIC life policy locator for a deceased relative you represent","https://eapps.naic.org/life-policy-locator/"],
  ["hk","Hong Kong: MPFA / old MPF trustees","https://www.mpfa.org.hk/en"],
  ["nofee","Do not pay a finder an upfront fee to claim your own money","https://www.usa.gov/unclaimed-money"]
];

window.CM_SOURCES = [
  ["USA.gov unclaimed money","Federal index of official databases","https://www.usa.gov/unclaimed-money"],
  ["NAUPA","State unclaimed-property administrators","https://unclaimed.org/search/"],
  ["MissingMoney","Multi-state search endorsed by NAUPA / NAST","https://missingmoney.com/"],
  ["IRS refunds","Where’s My Refund","https://www.irs.gov/refunds"],
  ["PBGC","Unclaimed private-sector pensions","https://www.pbgc.gov/workers-retirees/find-unclaimed-retirement-benefits/search-unclaimed"],
  ["DOL","Unpaid wages","https://webapps.dol.gov/wow/"],
  ["HUD","FHA insurance refunds","https://entp.hud.gov/dsrs/refunds/"],
  ["FDIC","Closed-bank unclaimed funds","https://closedbanks.fdic.gov/funds/"],
  ["NCUA","Closed credit-union deposits","https://ncua.gov/support-services/conservatorships-liquidations/unclaimed-deposits"],
  ["VA","Unclaimed VA life insurance","https://insurance.va.gov/UnclaimedFunds/Search"],
  ["NAIC","Life insurance policy locator","https://eapps.naic.org/life-policy-locator/"],
  ["US Courts","Bankruptcy unclaimed funds","https://ucf.uscourts.gov/"],
  ["SEC","Harmed-investor distributions","https://www.sec.gov/enforce/information-for-harmed-investors"],
  ["TreasuryDirect","I Bonds, TIPS. Treasury Hunt closed 30 Sep 2025","https://www.treasurydirect.gov/"],
  ["SAM.gov","Federal contracting / UEI","https://sam.gov/content/home"],
  ["FAR 13.2","Micro-purchase rules","https://www.acquisition.gov/far/subpart-13.2"],
  ["26 U.S.C. § 280A","Augusta / 14-day rental statute","https://www.law.cornell.edu/uscode/text/26/280A"],
  ["Volunteer.gov","Federal volunteer roles, some with lodging","https://volunteer.gov/"],
  ["BTFA / IIM","Individual Indian Money","https://www.doi.gov/ost/iim-accounts"],
  ["MPFA","Hong Kong MPF","https://www.mpfa.org.hk/en"],
  ["HK Official Receiver","Insolvency notices","https://www.oro.gov.hk/"]
];
